site_name: Linux Study Note
site_description: Linux Study Note

copyright: 'Copyright &copy; since 2018 Diwen Liu'

docs_dir: notes

repo_url: https://github.com/demon90s/LinuxStudy
edit_uri: "tree/master/notes"

nav:
  - Introduction: index.md
  - Chapters:
    - ch01 入门: ch01 入门.md
    - ch02 shell程序设计: ch02 shell程序设计.md
    - ch03 文件操作: ch03 文件操作.md
    - ch04 Linux环境: ch04 Linux环境.md
    - ch05 终端: ch05 终端.md
    - ch06 curses: ch06 curses.md
    - ch07 数据管理: ch07 数据管理.md
    - ch08 MySQL: ch08 MySQL.md
    - ch09 开发工具: ch09 开发工具.md
    - ch10 调试: ch10 调试.md
    - ch11 进程和信号: ch11 进程和信号.md
    - ch12 POSIX线程: ch12 POSIX线程.md
    - ch13 进程间通信_管道: ch13 进程间通信_管道.md
    - ch14 信号量_共享内存和消息队列: ch14 信号量_共享内存和消息队列.md
    - ch15 套接字: ch15 套接字.md
    - ch16 用GTK+进行GNOME编程: ch16 用GTK+进行GNOME编程.md
    - ch17 用Qt进行KDE编程: ch17 用Qt进行KDE编程.md
  - CheatSheet:
    - errno: cheatsheet/errno.md
    - Git-GitHub HowTo: cheatsheet/git_github-HowTo.md
    - Bash HowTo: cheatsheet/Bash-HowTo.md
    - CentOS7 HowTo: cheatsheet/CentOS7-HowTo.md
    - Ubuntu HowTo: cheatsheet/Ubuntu-HowTo.md
    - subversion HowTo: cheatsheet/subversion-HowTo.md
    - GDB HowTo: cheatsheet/GDB-HowTo.md
    - cmake HowTo: cheatsheet/cmake-HowTo.md
    - ssh HowTo: cheatsheet/ssh-HowTo.md
    - vim HowTo: cheatsheet/vim-HowTo.md

theme:
  #name: 'material'
  name: 'mkdocs'
  logo:
    icon: 'school'
  palette:
    primary: 'blue'
    accent: 'blue'
  font:
    text: 'PT Sans'
    code: 'PT Sans'
  language: 'zh'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.mark

google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'
