site_name: Linux Study Note
site_description: Linux Study Note

copyright: 'Copyright &copy; 2018 Diwen Liu'

docs_dir: notes

#repo_url: https://github.com/demon90s/LinuxStudy
#edit_uri: "tree/master/study_notes"

nav:
  - Introduction: index.md
  - Chapters:
    - ch01 入门: markdowns/ch01 入门.md
    - ch02 shell程序设计: markdowns/ch02 shell程序设计.md
    - ch03 文件操作: markdowns/ch03 文件操作.md
    - ch04 Linux环境: markdowns/ch04 Linux环境.md
    - ch05 终端: markdowns/ch05 终端.md
    - ch06 curses: markdowns/ch06 curses.md
    - ch07 数据管理: markdowns/ch07 数据管理.md
    - ch08 MySQL: markdowns/ch08 MySQL.md
    - ch09 开发工具: markdowns/ch09 开发工具.md
    - ch10 调试: markdowns/ch10 调试.md
    - ch11 进程和信号: markdowns/ch11 进程和信号.md
    - ch12 POSIX线程: markdowns/ch12 POSIX线程.md
    - ch13 进程间通信_管道: markdowns/ch13 进程间通信_管道.md
    - ch14 信号量_共享内存和消息队列: markdowns/ch14 信号量_共享内存和消息队列.md
    - ch15 套接字: markdowns/ch15 套接字.md
    - ch16 用GTK+进行GNOME编程: markdowns/ch16 用GTK+进行GNOME编程.md
    - ch17 用Qt进行KDE编程: markdowns/ch17 用Qt进行KDE编程.md
  - CheatSheet:
    - shell_utility: markdowns/cheatsheet/shell_utility.md
    - MySQL操作: markdowns/cheatsheet/MySQL操作.md
    - 用echo输出带颜色的文本: markdowns/cheatsheet/用echo输出带颜色的文本.md
    - 让进程在后台运行: markdowns/cheatsheet/让进程在后台运行.md
    - CentOS7软件安装: markdowns/cheatsheet/CentOS7软件安装.md

theme:
  name: 'material'
  logo:
    icon: 'school'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Open Sans'
    code: 'Open Sans Mono'
  language: 'zh'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.mark

google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'
